---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1nrjcewqfgp3apvnppmjj7sjelck029ur3tzelx9h7hr08d8jfymq2mhj6c"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1nrjcewqfgp3apvnppmjj7sjelck029ur3tzelx9h7hr08d8jfymq2mhj6c"
